# Generated by Django 5.1.12 on 2025-09-25 17:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='User profile picture', max_length=255, null=True, verbose_name='image'),
        ),
    ]
