# Generated by Django 5.1.12 on 2025-09-25 17:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Product image', max_length=255, verbose_name='image'),
        ),
    ]
