# Generated by Django 5.1.12 on 2025-09-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_categor_4083ff_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_seller__c70854_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_is_acti_cb485f_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsale',
            name='product_sal_seller__e939f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='productsale',
            name='product_sal_product_0fcb28_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='categories_is_acti_aae090_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent_category'], name='categories_parent__8fb5e1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_categor_9e60b3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller', 'is_active'], name='products_seller__04f073_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_created_e1ba5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='products_is_feat_19b203_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock_quantity'], name='products_stock_q_5d82ff_idx'),
        ),
        migrations.AddIndex(
            model_name='productsale',
            index=models.Index(fields=['seller', 'sale_date'], name='product_sal_seller__8a9825_idx'),
        ),
        migrations.AddIndex(
            model_name='productsale',
            index=models.Index(fields=['product', 'sale_date'], name='product_sal_product_afe108_idx'),
        ),
    ]
